name: Deploy to Contabo VPS

on:
  push:
    branches:
      - simulation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_LOGIN }}
          script: |
            cd /var/www/rocket-lms
            git pull origin simulation
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force

            # Clear and rebuild caches
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear


            php artisan storage:link || true

            chown -R www-data:www-data storage bootstrap/cache public
            chmod -R 775 storage bootstrap/cache public

            systemctl restart apache2
#

