name: Deploy to Contabo VPS

on:
  push:
    branches:
      - simulation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /var/main/rocket-lms
            git pull origin simulation
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear

            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache
            
            systemctl restart apache2
